FROM mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye

# Install dependencies for Electron and Playwright
# Based on Playwright documentation for Debian/Ubuntu
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \
    libnss3 \
    libnspr4 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libdrm2 \
    libxkbcommon0 \
    libxcomposite1 \
    libxdamage1 \
    libxfixes3 \
    libxrandr2 \
    libgbm1 \
    libasound2 \
    libpangocairo-1.0-0 \
    libpango-1.0-0 \
    libcairo2 \
    libgtk-3-0 \
    libxshmfence1 \
    && apt-get clean -y && rm -rf /var/lib/apt/lists/*
